<table>
    <tr>
        <td>Name</td>
        <td>$_POST['name']</td>
    </tr>
    <tr>
        <td>Name</td>
        <td>$_POST['name']</td>
    </tr>
    <tr>
        <td>Name</td>
        <td>$_POST['name']</td>
    </tr>
    <tr>
        <td>Name</td>
        <td>$_POST['name']</td>
    </tr>
</table>