<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');


class Register extends CI_Controller {

    public function __construct(){
          parent::__construct();
         $this->load->model('common_model');
         $this->load->library(['auth', 'session']);
         $this->load->library('form_validation');
         if(check()){
           $this->session->set_flashdata(array('massege' => 'Your Registration is done', 'status' => 1));
           $this->load->view('registerDone');
         }
    }


    public function index() {

       $this->load->view('register');
    }
     public function Signup() {
      if($_POST){
          $data =  $this->security->xss_clean($_POST); // cleaning proccess for POST data from view
          $check = $this->common_model->check_user($data); // check if user is aleady exist
        if($check) {
          $data['user']=$check;
          $this->load->view('user',$data);
        } else {
          if(ctype_digit($data['username'])) {
            $phone = $data['username'];
            $email = null;
          } else {
            $phone = null;
            $email = $data['username'];
          }
          $pass = password_hash($data["password"], PASSWORD_DEFAULT);  // Password Default
          $text = getCustomId($this->common_model->get_last_id('logme'), 'EDO');
          //echo $text;exit;
          $message = [
            'logid' => $text, // Automatically generated by the model
            'email' => $email,
            'phone' => $phone,
            'password' => $pass,
            'status' => 'active',
            'role' => 's',
            'joindate' => current_datetime(),
          ];
          $str = $this->common_model->insert($message,'logme');
          if($str!='') {
            $details = [
              "user_id" => $text,
              "name" => $data['fullname']
            ];
            $this->common_model->insert($details,'user_details');
            $this->common_model->insert(array('user_id' => $text, 'role_id' => 2),'roles_users');
            $this->common_model->insert(array('root' => $text), 'thumbnail');
            $loginData = [
              'username' => ($email != null) ? $email : $phone,
              'password' => 'kalka@'.$text,
            ];
            $temp = $this->auth->login($loginData);
            if($temp['status']){
              $this->session->set_flashdata(array('massege' => 'Registration', 'status' => 1));
              redirect(base_url() . 'join', 'refresh');
            }
          } else {
            $temp="Try again";
            $this->session->set_flashdata(array('massege' => 'Registration Faild. check your Email or Phone or try again.', 'status' => 0));
            redirect(base_url() . 'authentication', 'refresh');
          }
        }
      }
    }

     public function subscribe() {
      if($_POST){
          $data =  $this->security->xss_clean($_POST); // cleaning proccess for POST data from view
          $check = $this->common_model->check_user($data); // check if user is aleady exist
        if($check) {
          $data['user'] = $check;
          $this->load->view('user',$data);
        } else {
          if(ctype_digit($data['username'])) {
            $phone = $data['username'];
            $email = null;
          } else {
            $phone = null;
            $email = $data['username'];
          }
          $text = getCustomId($this->common_model->get_last_id('logme'), 'EDO');
          $pass = password_hash('kalka@' . $text, PASSWORD_DEFAULT);  // Password Default  kalka@$text
          $message = [
            'logid' => $text, // Automatically generated by the model
            'email' => $email,
            'phone' => $phone,
            'password' => $pass,
            'status' => 'active',
            'role' => 's',
            'joindate' => current_datetime(),
          ];
          $str = $this->common_model->insert($message,'logme');
          if($str!='') {
            $lead = [
              'city' => $data['city'],
              'request_course' =>  $data['course']
            ];
            $details = [
              "user_id" => $text,
              "name" => $data['fullname'],
              "details" => json_encode($lead),
            ];
            $this->common_model->insert($details,'user_details');
            $this->common_model->insert(array('user_id' => $text, 'role_id' => 2),'roles_users');
            $this->common_model->insert(array('root' => $text), 'thumbnail');
            $_POST = [
              'username' => ($email != null) ? $email : $phone,
              'password' => 'kalka@'.$text,
            ];
            $temp = $this->auth->login($_POST);
            if($temp['status']) {
              $this->session->set_flashdata(array('massege' => 'Registration', 'status' => 1));
              redirect(base_url() . 'join', 'refresh');
            }
          } else {
            $temp="Try again";
            $this->session->set_flashdata(array('massege' => 'Registration Faild. check your Email or Phone or try again.', 'status' => 0));
            redirect(base_url() . 'authentication', 'refresh');
          }
        }
      }
    }
 
}
